<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PhotoOrganizer.Crawler\PhotoOrganizer.Crawler.csproj" />
    <ProjectReference Include="..\..\src\PhotoOrganizer.Server\PhotoOrganizer.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\fixtures\photos\**\*" CopyToOutputDirectory="PreserveNewest">
      <Link>fixtures\photos\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
</Project>
